services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: syntax_admin
      POSTGRES_PASSWORD: syntax_admin
      POSTGRES_DB: SyntaxDb
    ports:
      - 5432:5432
    networks:
      - syntax-network
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  flyway:
    image: flyway/flyway
    entrypoint: ["bash"]
    command: -c /flyway/sql/migrate.sh
    volumes:
      - ./Syntax.Core/Migrations:/flyway/sql
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - syntax-network

  # Completely optional, but here as an example if needed
  syntax-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:8080
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - syntax-network

networks:
  syntax-network:
    driver: bridge 

volumes:
  pg_data:
    driver: local
