services:
  syntax-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - syntax-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: syntax_admin
      POSTGRES_PASSWORD: syntax_admin
      POSTGRES_DB: SyntaxDb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - syntax-network

networks:
  syntax-network:
    driver: bridge

volumes:
  pg_data:
    driver: local
